sodo: required

services: docker

before_install:
  - docker-compose up --build -d #for test
  - docker login -u '$HEROKU_USERNAME' -p '$HEROKU_API_KEY' registry.heroku.com #for deploy

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

deploy:
  provider: scirpt
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod. ;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master #deploy only when merged to master